title: Copilot Studio SSO Documentation
description: Documentation for configuring Single Sign-On (SSO) with Copilot Studio
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - .github
  - docs/assets
  - docs/sso/troubleshooting.md
  - docs/sso/index.md
  - docs/index.md